spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ffffffffffffffffffffffffff
            client-secret: ffffffffffffffffffffffffffffSS
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          