spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 693765673163-ndqng1usdt8mrdsg61d2dg7bgbmmpgko.apps.googleusercontent.com
            client-secret: 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
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          